# Generated by Django 3.1.2 on 2021-03-26 17:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(null=True)),
                ('semester', models.IntegerField(null=True)),
                ('subject', models.CharField(max_length=256, null=True, verbose_name='Studienfach')),
                ('degree', models.CharField(max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(max_length=256, null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('gender', models.CharField(max_length=256, null=True)),
                ('additional_data', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('sequence', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=list, size=None)),
                ('classname', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=512)),
                ('answer', models.CharField(max_length=2048)),
                ('type', models.CharField(max_length=128, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.study'),
        ),
        migrations.AddField(
            model_name='participant',
            name='operating_system',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='screen_size',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='browser_language',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questionnaire', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=256)),
                ('latent_variable', models.CharField(max_length=256)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('given_answer', models.CharField(max_length=256, null=True)),
                ('reverse_coded', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tree_id', models.IntegerField(verbose_name='Zielbaum ID')),
                ('parent_id', models.IntegerField(default=None, null=True, verbose_name='Oberziel')),
                ('title', models.CharField(max_length=20, verbose_name='Zieltext')),
                ('description', models.CharField(max_length=512, null=True, verbose_name='Beschreibung')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.participant')),
                ('is_example', models.BooleanField(default=False)),
                ('example_id', models.IntegerField(default=None, null=True)),
                ('condition', models.CharField(max_length=256, null=True)),
                ('study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.study')),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('route', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=256)),
                ('participant',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.participant')),
            ],
        ),
        migrations.CreateModel(
            name='StudyContext',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('view', models.CharField(max_length=256)),
                ('context', models.JSONField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.study')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Zieltext')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.participant')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.goal'),
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.goal'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.item'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.question'),
        ),
    ]
