# Generated by Django 3.1.2 on 2021-06-03 12:32

from django.db import migrations

def change_root_tree_id(apps, schema_editor):
    Goal = apps.get_model("construction", "Goal")

    Goal.objects.filter(parent_id=0).update(parent_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_userinteraction_duration'),
    ]

    operations = [
        migrations.RunPython(change_root_tree_id)
    ]
