# Generated by Django 3.1.2 on 2021-06-28 16:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_change_root_tree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
