# Generated by Django 3.1.2 on 2021-07-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_study_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='siddata_user_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
