# Generated by Django 3.1.2 on 2021-07-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_study_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.goal'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.item'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.question'),
        ),
    ]
