# Generated by Django 3.1.2 on 2021-07-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_auto_20210707_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='target_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
