# Generated by Django 3.1.3 on 2021-07-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_userinteraction_target_id'),
        ('construction', '0006_participant_siddata_user_id'),
    ]

    operations = [
    ]
