# Generated by Django 3.1.2 on 2021-07-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_merge_20210709_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='discarded',
            field=models.BooleanField(default=False),
        ),
    ]
