# Generated by Django 3.1.2 on 2021-07-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0011_item_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='study_sequence_position',
            field=models.IntegerField(null=True),
        ),
    ]
