# Generated by Django 3.1.2 on 2021-08-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0012_participant_study_sequence_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Zieltext'),
        ),
    ]
