# Generated by Django 3.1.2 on 2021-08-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0013_auto_20210803_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='done',
            field=models.BooleanField(null=True),
        ),
    ]
