# Generated by Django 3.1.2 on 2021-09-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0014_goal_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Zieltext'),
        ),
        migrations.AlterField(
            model_name='personalgoal',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Zieltext'),
        ),
    ]
