# Generated by Django 3.1.2 on 2021-09-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0016_goal_replicated_tree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='language',
            field=models.CharField(default='de', max_length=16),
        ),
    ]
