# Generated by Django 3.1.2 on 2022-03-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0017_study_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='exclude_from_analyses',
            field=models.BooleanField(default=False),
        ),
    ]
