# Generated by Django 3.1.2 on 2022-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0018_participant_exclude_from_analyses'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study',
            name='description',
            field=models.CharField(max_length=512, null=True, unique=True),
        ),
    ]
