# Generated by Django 3.1.2 on 2022-05-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0019_auto_20220509_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
