# Generated by Django 3.1.2 on 2022-05-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0020_study_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='origin',
            field=models.CharField(default='sirdata', max_length=64),
        ),
        migrations.AddField(
            model_name='participant',
            name='origin_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
